# netlify.toml

[build]
  command = "yarn run build"     # Command to build your React app
  publish = "build/"           # Directory to publish (the output of the build process)

[[redirects]]
  # Optionally, you can specify redirects for your app
  # This is useful for handling client-side routing in single-page apps
  from = "/*"
  to = "/index.html"
  status = 200
